Remove all things pyscriptjs

diff --git a/.github/workflows/test-next.yml b/.github/workflows/test-next.yml
--- a/.github/workflows/test-next.yml
+++ b/.github/workflows/test-next.yml
@@ -6,8 +6,6 @@ on:
             - next
         paths:
             - pyscript.core/**
-            - pyscriptjs/**
-            - examples/**
             - .github/workflows/test-next.yml # Test that workflow works when changed
 
     pull_request: # Run on any PR that modifies files under pyscriptjs/ and examples/
@@ -15,20 +13,15 @@ on:
             - next
         paths:
             - pyscript.core/**
-            - pyscriptjs/**
-            - examples/**
             - .github/workflows/test-next.yml # Test that workflow works when changed
     workflow_dispatch:
 
 jobs:
     TestNext:
-        runs-on: ubuntu-latest-8core
+        runs-on: ubuntu-latest
         defaults:
             run:
-                working-directory: pyscriptjs
-        env:
-            MINICONDA_PYTHON_VERSION: py38
-            MINICONDA_VERSION: 4.11.0
+                working-directory: pyscript.core
         steps:
             - name: Checkout
               uses: actions/checkout@v3
@@ -36,7 +29,7 @@ jobs:
             - name: Install node
               uses: actions/setup-node@v3
               with:
-                  node-version: 18.x
+                  node-version: 20.x
 
             - name: Cache node modules
               uses: actions/cache@v3
@@ -51,21 +44,6 @@ jobs:
                       ${{ runner.os }}-build-
                       ${{ runner.os }}-
 
-            - name: setup Miniconda
-              uses: conda-incubator/setup-miniconda@v2
-
-            - name: Setup Environment
-              run: make setup
-
-            - name: Build
-              run: make build
-
-            - name: TypeScript Tests (core)
-              run: make test-ts
-
-            - name: Python Tests
-              run: make test-py
-
             - name: install next deps
               working-directory: pyscript.core
               run: npm i
@@ -78,31 +56,26 @@ jobs:
               working-directory: pyscript.core
               run: npm run test
 
-            - name: Integration Tests
-              run: make test-integration-parallel
+            # TODO: DO we want to upload next yet?
+            # - uses: actions/upload-artifact@v3
+            #   with:
+            #       name: pyscript
+            #       path: |
+            #           pyscriptjs/build/
+            #       if-no-files-found: error
+            #       retention-days: 7
 
-            - name: Examples Tests
-              run: make test-examples
-
-            - uses: actions/upload-artifact@v3
-              with:
-                  name: pyscript
-                  path: |
-                      pyscriptjs/build/
-                  if-no-files-found: error
-                  retention-days: 7
-
-            - uses: actions/upload-artifact@v3
-              if: success() || failure()
-              with:
-                  name: test_results
-                  path: pyscriptjs/test_results
-                  if-no-files-found: error
+            # - uses: actions/upload-artifact@v3
+            #   if: success() || failure()
+            #   with:
+            #       name: test_results
+            #       path: pyscriptjs/test_results
+            #       if-no-files-found: error
     eslint:
         runs-on: ubuntu-latest
         defaults:
             run:
-                working-directory: pyscriptjs
+                working-directory: pyscript.core
         steps:
             - name: Checkout
               uses: actions/checkout@v3
@@ -110,7 +83,7 @@ jobs:
             - name: Install node
               uses: actions/setup-node@v3
               with:
-                  node-version: 18.x
+                  node-version: 20.x
 
             - name: Cache node modules
               uses: actions/cache@v3
